image:
  file: .gitpod.Dockerfile

tasks:
  - before: export WAS9_HOME=/opt/IBM/WebSphere/AppServer
    init: mvn clean compile
    command: . /opt/IBM/WebSphere/AppServer/profiles/AppSrv01/bin/setupCmdLine.sh && /opt/IBM/WebSphere/AppServer/profiles/AppSrv01/bin/startServer.sh server1
